filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_host_metadata: ~
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "kyc-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: false
setup.template.name: "kyc-logs"
setup.template.pattern: "kyc-logs-*"

logging.level: warning
